image: andreipoe/buildpack-cpp:20.04

stages:
  - build
  - test


.build:meson:
  stage: build
  script:
    - meson build
    - ninja -C build
  artifacts:
    paths:
      - build
    expire_in: 1 day

.test:meson:
  stage: test
  script:
    - cd build
    - ./scs-test


build:meson:gcc:
  extends: .build:meson
  variables:
    CXX: g++

test:meson:gcc:
  extends: .test:meson
  needs:
    - build:meson:gcc


build:meson:clang:
  extends: .build:meson
  variables:
    CXX: clang++

test:meson:clang:
  extends: .test:meson
  needs:
    - build:meson:clang


.build:make:
  stage: build
  script:
    - make -j COMPILER=$COMPILER
  artifacts:
    untracked: true
    expire_in: 1 day

.test:make:
  stage: test
  script:
    - touch *.o # Otherwise base objects will be rebuilt, too
    - make -j COMPILER=$COMPILER test
    - ./test/scs-test


build:make:gcc:
  extends: .build:make
  variables:
    COMPILER: GNU

test:make:gcc:
  extends: .test:make
  variables:
    COMPILER: GNU
  needs:
    - build:make:gcc


build:make:clang:
  extends: .build:make
  variables:
    COMPILER: CLANG

test:make:clang:
  extends: .test:make
  variables:
    COMPILER: CLANG
  needs:
    - build:make:clang
