image: andreipoe/buildpack-cpp:20.04

stages:
  - basic build
  - more builds

gcc:
  stage: basic build
  script:
    - make -j COMPILER=GNU
    - make -j COMPILER=GNU test
    - ./test/scs-test

clang:
  stage: more builds
  script:
    - make -j COMPILER=CLANG
    - make -j COMPILER=CLANG test
    - ./test/scs-test

meson:
  stage: more builds
  script:
    - env CXX=g++ meson build-gnu
    - cd build-gnu
    - ninja
    - ./scs-test
